FROM openjdk:17-jdk-slim

VOLUME /tmp

ARG JASYPT_KEY

ENV JASYPT_KEY=${JASYPT_KEY}

COPY xcape-admin/build/libs/xcape-admin-1.0-SNAPSHOT.jar xcape-admin.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Djasypt.encryptor.password=${JASYPT_KEY}", "-jar", "xcape-admin.jar"]